### PR TITLE
More details about 3rd-party libs

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Review by SarikaSinha — APPROVED** [review]
We should also suggest how to handle these errors in any saved place like Build Path etc.
How can we get the actions automated?

**Comment by mickaelistria** [comment]
> We should also suggest how to handle these errors in any saved place like Build Path etc.

I don't think that the `org.junit....` artifact names is usually saved in the Build Path. They either come from Maven, or from the .target or from the JUnit Classpath Container (which is dynamically re-computed on startup I believe). Can you please elaborate on the particular cases you think require further assistance?

**Comment by SarikaSinha** [comment]
> > We should also suggest how to handle these errors in any saved place like Build Path etc.
> 
> I don't think that the `org.junit....` artifact names is usually saved in the Build Path. They either come from Maven, or from the .target or from the JUnit Classpath Container (which is dynamically re-computed on startup I believe). Can you please elaborate on the particular cases you think require further assistance?

This was not for junit in particular. As in future we will be doing for other jars as well.
For junit in particular I observed the issues coming after Export-Import as it saves the references.

**Comment by laeubi** [comment]
The JUnit container specifically searches for `org.junit` bundle name in the installation see:

 https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/fc4e491a077e0e1fc43dade3b7cadfca963449be/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java#L302 

also see
- https://github.com/eclipse/tycho/issues/1164

**Comment by mickaelistria** [comment]
> The JUnit container specifically searches for org.junit bundle name in the installation see:

That's JUnit 4 and there are no OSGi alternative to Orbit's JUnit 4 . So this bundle is here to stay and was not removed from target nor feature.
In lines following the one you link, you can see that the org.junit.platform/jupiter bundles were changed.

**Comment by mickaelistria** [comment]
> For junit in particular I observed the issues coming after Export-Import as it saves the references.

Where are those references saved? Can you please add details about how to reproduce?

**Comment by SarikaSinha** [comment]
> > For junit in particular I observed the issues coming after Export-Import as it saves the references.
> 
> Where are those references saved? Can you please add details about how to reproduce?

Sorry, Looks like a false alarm, Import was not building due to some other mismatch.

**Pull request merged**
