### PR TITLE
Use org.glassfish.web.javax.servlet.jsp

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
I'll revert this one as CI didn't pass actually ( https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-106/ ), but the result was not reported to CI.

**Comment by mickaelistria** [comment]
But what's strange is that master got successful: https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/master/123/

**Comment by laeubi** [comment]
I see

> [WARNING] org.glassfish:javax.el/maven-metadata.xmlfailed to transfer from https://maven.java.net/content/repositories/releases/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of jvnet-nexus-releases has elapsed or updates are forced. Original error: Could not transfer metadata org.glassfish:javax.el/maven-metadata.xml from/to jvnet-nexus-releases (https://maven.java.net/content/repositories/releases/): transfer failed for [https://maven.java.net/content/repositories/releases/org/glassfish/javax.el/maven-](https://maven.java.net/content/repositories/releases/org/glassfish/javax.el/maven-metadata.xml)

in the logs, so probably this was an network issue instead?

**Comment by mickaelistria** [comment]
This is actually the change in the feature https://github.com/eclipse-platform/eclipse.platform.releng/pull/213 which impacts that actual version of jasper embedded in the SDK, thus that cause the failure or not.

**Pull request merged**
