### PR TITLE
Migrate to javax.inject/annotation provided by Jakarta from Maven-Ctrl.

### PR DESCRIPTION
**Pull request by HannesWell**
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056

### CODE REVIEW

**Comment by HannesWell** [comment]
@akurtakov or @mickaelistria can you tell how I have to adjust this PR to make the verification build in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1057 (which is modified to include this PR) can succeed?
At the moment it fails with

```
[INFO] --- tycho-compiler:4.0.0-SNAPSHOT:compile (default-compile) @ org.eclipse.platform.doc.isv ---
[INFO] 
[INFO] --- tycho-eclipserun:4.0.0-SNAPSHOT:eclipse-run (dont_skip_me) @ org.eclipse.platform.doc.isv ---
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install 'osgi.bundle; jakarta.annotation-api 0.0.0' but it could not be found
```

**Comment by akurtakov** [comment]
I don't see jakarta.annotation-api in the target platform https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target thus adding it there is the first thing I would try.

**Comment by merks** [comment]
Yes, it probably needs to be the bundle name not the artifact ID...

**Comment by laeubi** [comment]
> What I'm not sure about is, if the artifactId needs to be the Bundle-SymbolicName or something else?

Its always the Bundle-**Symbolic**Name ...

The BSN for https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api/1.3.5 is:

`Bundle-SymbolicName: jakarta.annotation-api`

While the bundle name is:

`Bundle-Name: Jakarta Annotations API`

**Comment by HannesWell** [comment]
Although the overall build in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1059 failed, the changed co bundles were build successfully. So I think this is ready to go.

**Pull request merged**
