### PR TITLE
Updates IDE picture with a recent version of the Eclipse IDE

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by laeubi** [comment]
As long as "Dark Mode" is not the default I think its not appropriate to have "dark" images in the help. @merks what do you think?

**Comment by merks** [comment]
@laeubi 

Yes, I'm really unhappy that we are messing with documentation.  Consistency across all the documentation is more important than sharing those images elsewhere outside of the documentation.  And yes, I don't think dark theme should be used in the documentation.

**Comment by merks** [comment]
@vogella 

Please reconsider this task.   I don't think this is a worthwhile goal at this point with so much else to do.  The images may be outdated, but they are consistently so...

**Comment by vogella** [comment]
> Please reconsider this task. I don't think this is a worthwhile goal at this point with so much else to do. The images may be outdated, but they are consistently so...

No they are not consistent, some are still on super old Windows, some of on Mac, some are on Linux. Some are in the light theme, some are in the dark theme, see for example the N&N. I think it is also important to show the differnent themes in the documentation, as Eclipse supports all these.

**Comment by mickaelistria** [comment]
I agree here. Consistency in documentation pictures was never achieved and won't ever be without tremendous effort (ie someone going through all pictures of the help and adjusting them to new layout). That effort is hardly profitable.
On the other hand, updating one image at a time with a current image that seems most appropriate to the context is profitable.
So I think we have better chance to increase value by changing images progressively and let them have different themes/OS than by enforcing a rule for standardization we won't be able to implement anyway.

**Pull request merged**
