### PR TITLE
Stop shipping prebuild help indexes

### PR DESCRIPTION
**Pull request by akurtakov**
Fixes https://github.com/eclipse-platform/.github/issues/130

### CODE REVIEW

**Comment by akurtakov** [comment]
> Shouldn't there be some script code that generates the index files and that is now obsolete?

This is why tycho-document-bundle-plugin was invoked and is no longer invoked with this patch. This doesn't built the index anymore as I got local failures until editing build.properties to remove index/ entry. If I'm missing something else please point me to it.

**Comment by iloveeclipse** [comment]
> If I'm missing something else please point me to it.

No idea, just guessed there must be some ant build that does the job, since many of "doc" tasks were ant based.

**Comment by laeubi** [comment]
>> If I'm missing something else please point me to it.
> 
> No idea, just guessed there must be some ant build that does the job, since many of "doc" tasks were ant based.

Generation of the index was recently moved from ant-scripts to `tycho-document-bundle-plugin`

**Comment by akurtakov** [comment]
I'm merging this one and starting new I-build as doc bundles are especially touchy.

**Comment by laeubi** [comment]
@akurtakov I noticed with the eclipse-sdk-ide that I get every few minutes a doc build like this:

grafik

this is quite annoying as it grabs focus and hides the console can we disable these automatic ant scripts as well (I have no clue where they are coming from)

**Comment by merks** [comment]
Funny but I don't have that ECF project in my workspace:

image

Probably you can remove from the build.properties the reference to the ant file that's causing this to kick in.

**Comment by laeubi** [comment]
This is what my current install shows ( I have no idea how /why this was included):
grafik

as it is running approx every 1 or two minutes its quite annoying neverless... do we really need the sources? Should then not be provided by the target platform if ECF is not "platform" but dependency?

**Comment by merks** [comment]
Perhaps at some point you manually imported all the projects from that Git repository.

My picture was from a fresh new SDK install from today.

No, you don't need them, but the point of the the full SDK step is to include all the source of all the projects that are shipped with the Eclipse SDK product, so that includes parts of ECF and parts of EMF. 

If you don't want them, you can close the projects and they won't be reopened.

**Pull request merged**
