### PR TITLE
Add new JDT api option: COMPILER_IGNORE_UNNAMED_MODULE_FOR_SPLIT_PACKAGE 

### PR DESCRIPTION
**Pull request by jdneo**
See: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/424

### CODE REVIEW

**Comment by mickaelistria** [comment]
Signed-Off-By isn't required (but it's OK to keep it if you prefer)

**Comment by jdneo** [comment]
@mickaelistria The sign-off is removed.

@stephan-herrmann Here is the PR for document update.

**Comment by laeubi** [comment]
@stephan-herrmann make sure that you have entered your github name in your eclipse profile under "social links", then usually it takes some hours for the sync scripts to run and you get an invitation to join all projects you are committer on.

**Comment by laeubi** [comment]
By the way you can still goto "File changed" > "Approve" ... I would even merge this but I'm not sure because of M3 freeze period here... @mickaelistria @akurtakov ?

**Comment by akurtakov** [comment]
@stephan-herrmann is not platform committer and all the "workarounds" and shared groups and etc. are gone now for good thus he can't merge.
Documentation changes and etc. are fine to merge IMHO and I'll do it as per Stephan's approval.

**Pull request merged**
